service: i-won-nike-draws
useDotenv: true
frameworkVersion: "2"

provider:
  name: aws
  runtime: python2.7
  region: ap-northeast-2

functions:
  crawl:
    handler: handler.crawl
    events:
      - schedule: cron(0 8 * * ? *)

