service: i-won-nike-draws
useDotenv: true
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  crawl:
    handler: handler.crawl
    events:
      - schedule: cron(0 8 * * ? *)
    environment:
      WEBHOOK_URL: ${opt:webhookUrl}
      

